### PR TITLE
Repo and site restructure.

### PR DESCRIPTION
**Pull request by johnnymatthews**
Based on @LexLuthr's [branch](https://github.com/filecoin-project/lotus-docs/pull/68). Creating a new PR so we can get a fancy preview.

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Well, something's gone wrong. The preview is all messed up and none of the CSS is showing...

image

**Comment by jennijuju** [comment]
How dare you ruin our fancy docs!

**Comment by jennijuju** [comment]
I don’t think ruin lotus doc is in your jd :trollface:

**Comment by jennijuju** [comment]
Carrying over from the other PR - yah I don’t think we should call it client. Maybe “installing a lotus client/node” - then expand to, a lotus client/node may run daemon & client (filecoin client)

**Comment by LexLuthr** [comment]
It was working before in the preview of other PR. I will try to pull it and deploy locally to check what went wrong.
Could it be a netifly problem?

**Comment by LexLuthr** [comment]
Everything is working as expected locally on my PC. @johnnymatthews  Can you check if this is a netifly issue.
I checked some articles on the netifly and it seems the script and other data are being called from https://lotus.filecoin.io/favicon-32x32.png and this violates the "self-src" policy. How are these items being deployed for the preview? When deploying locally they are referred correctly via https://localhost. Could it be because we are setting "baseURL" implicitly? Can we try to deploy by setting it explicitly and check if the problem persists?

**Comment by johnnymatthews** [comment]
> Everything is working as expected locally on my PC. 

Same :sweat_smile:. Everything works perfectly, but for some reason when it's built using `npm run build` and served from somewhere, it fails. It even fails when running a local server (that isn't hugo):

```shell
npm install -g serve
cd lotus-docs
npm install
npm run build
cd public
serve
```

I've ran into something like this before, when we first started playing around with Lotus docs, but I can't remember what the fix was. I'll have to dig into things and figure out what's going on.

> Could it be because we are setting "baseURL" implicitly?

I thought that too, but the `main` branch of this repo builds fine (locally using serve, using Fleek, or using Netlify), and that's got the `baseURL` set to `lotus.filecoin.io`: https://github.com/filecoin-project/lotus-docs/blob/main/config/_default/config.toml#L1

**Comment by jennijuju** [comment]
@johnnymatthews I tends to agree with @LexLuthr here, seems like https://github.com/filecoin-project/lotus/issues/8106#issuecomment-1050934658 was working fine before the migration.
this project is a P1 for lotus TSE team and im afraid creating a new Dok project will block us -  can we spend more time to debug it or revert to the previous working PR?

**Comment by bry81** [comment]
gh pr checkout 82

**Comment by johnnymatthews** [comment]
This PR is ready for review now @LexLuthr!

- All the files are in.
- All relref links and working.
- The structure matches the new map design.
- Each page has an alias to it's corresponding page in the current `lotus.filecoin.io` docs build.
- Some front end stuff has been updated and fixed.

**Review by LexLuthr — COMMENTED** [review]
@johnnymatthews Hey, I checked the preview and there a lot of changes from my PR in terms to content as well as structuring.
1. KB section is gone altogether. This was the major change we needed in the docs.
2. Tutorials seems to be broken down to fit what content is already in the docs. I broke it into lotus and miner sections to accommodate future pages. I have created a tutorials on how to run a miner and how to add a worker specifically for this.
3. Sub heading under developers don't make much sense to me. We simply don't have enough content to create sub-menu headings as of yet. Perhaps, we can create those in future when this section has more content?

**Comment by johnnymatthews** [comment]
> KB section is gone altogether.

I've just hidden the menu item, so we can add it back in easily. I removed it because it looks pretty empty right now, and essentially looks unfinished. But if it's absolutely necessary that it's not hard to add back in.

> Tutorials seems to be broken down to fit what content is already in the docs.

Having the tutorials section split into just `lotus` and `lotus-miner` works, if the tutorials are tiny. But long for tutorial like Store & retrieve are really hard to go through in one big page. That's why I split things into individual sections. The tutorials we have under **Lotus** right now look more like _user guides_ rather than full on tutorials. The difference between the two is that _user guides_ tell you how to do one specific thing (add data to something, install an app, send a Curl request to a server). Whereas tutorials tell you how to get to a complex end-goal while covering multiple individual actions (Store & retrieve tells you how to install Lotus, store some data, navigate the Miner Registries, and download some data).

> Sub heading under developers don't make much sense to me. 

Yeah I agree here. But having **Developers** at the top and then **Developers** on the sidebar seemed a bit silly. Maybe the user guides I just mentioned (store, retrieve, import data from IPFS, etc) can go into this **Developers** topbar nav section. Thoughts?

**Comment by LexLuthr** [comment]
> > KB section is gone altogether.
> 
> I've just hidden the menu item so that we can add it back in quickly. I removed it because it looks pretty empty right now and essentially looks unfinished. But if it's absolutely necessary that it's not hard to add back in.
> 

Can we please add it back? It won't be empty for more than a few hours. We have articles ready at https://sgtcoin.github.io/everest-web/articles/full/ to be moved. It will be a very quick PR.

> > Tutorials seems to be broken down to fit what content is already in the docs.
> 
> Having the tutorials section split into just `lotus` and `lotus-miner` works if the tutorials are tiny. But long for a tutorial like "Store & retrieve" are really hard to go through in one big page. That's why I split things into individual sections. The tutorials we have under **Lotus** right now look more like _user guides_ rather than full-on tutorials. The difference between the two is that _user guides_ tell you how to do one specific thing (add data to something, install an app, send a Curl request to a server). At the same time, tutorials tell you how to get to a complex end goal while covering multiple individual actions ("Store & retrieve" tells you how to install Lotus, store some data, navigate the Miner Registries, and download some data).
> 

Hey, I have 2 mining tutorials ready. One is about setting up a miner in calibnet and other is about adding seal-worker to that miner. I can't directly add them to this branch as it is protected branch. I can create a new branch and open a PR on this feat branch. Lotus and Lotus-Miner are umbrella. I will be adding tutorials about running simple API operation on lotus as well. I keep getting a lot of requests about that. If this plans sounds good, then please revert the changes and I will open the PR with 2 new tutorial content to begin with.

Some of these tutorials are repetitive and don't add any true values. My suggestions:

1. Store data - Hide this one. I will review it once this PR is merged and move any important content to Number 7.
2. Retrieve data - Hide this one. I will review it once this PR is merged and move any important content to Number 8.
3. Import data from IPFS - Keep this one under "Lotus Tutorials"
4. Large files -  Keep this one under "Lotus Tutorials". But this will require a review. 
5. Payment channels - Move payment channels to "Manage" sub-section under "Lotus" Section as this page has informative content and not just a tutorial.
6. Set up - Move under "Lotus Tutorials"
7. Store data - Move under "Lotus Tutorials"
8. Retrieve data - Move under "Lotus Tutorials"

> > Sub heading under developers don't make much sense to me.
> 
> Yeah, I agree here. But having **Developers** at the top and then **Developers** on the sidebar seemed a bit silly. Maybe the user guides I just mentioned (store, retrieve, import data from IPFS, etc) can go into this **Developers** topbar nav section. Thoughts?

Let's Keep the developers section as your have structured it for now. Once we have more content, we can move stuff around. Docs are ever changing as required. So no need to get everything done at once. 

We are almost there. If you agree with my suggestions then please go ahead and merge this PR so I can start creating PRs for the next set of content like miner tutorials, KB articles etc. 

Next big change would be opening blogs sections. I will check with community about it as I want to move show and tell, best practices etc out of discussions and move them to blogs.

**Comment by LexLuthr** [comment]
@johnnymatthews Can you please go through my last review and move forward with the merge if you agree? I have multiple projects waiting on this merge. 

Document how to sign messages using a remote lotus node P3
Add details about CGroup variables and their effects P2
Audit and Revise Lotus Section in Lotus docs dif/expert effort/weeks P1
Audit and Revise Storage Providers Section in Lotus docs dif/medium effort/weeks P1

I don't see any major blockers either on this merge.

@jennijuju Would you like to do a final review?

**Comment by johnnymatthews** [comment]
I've unhidden the KB section.

I'm a bit confused about what you'd like to see in the **Tutorials** section, so I've left that how I structured it for now. I'm happy to merge this in now.

**Comment by LexLuthr** [comment]
@johnnymatthews Merge it for now. I will file a new PR with tutorials and new structure as well. We can review it then.

**Pull request merged**
