### PR TITLE
add partial retrieval CLI and update client CLI

### PR DESCRIPTION
**Pull request by LexLuthr**
Fixes https://github.com/filecoin-project/lotus-docs/issues/51

### CODE REVIEW

**Comment by jennijuju** [comment]
I think we will need more detailed user examples

**Comment by LexLuthr** [comment]
> I think we will need more detailed user examples

@jennijuju , I was thinking of adding partial retrieval under tutorials. It seems like the best place for examples.

**Comment by jennijuju** [comment]
I highly recommend we start to add more client side of documentation to lotus doc.

**Comment by johnnymatthews** [comment]
This PR looks fine from my end. Thanks!

>  I was thinking of adding partial retrieval under tutorials - @LexLuthr 

This would be super useful. Using Lotus, from a clients perspective, is pretty daunting. Before you start creating a tutorial though, let's make an issue first.

> start to add more client side of documentation - @jennijuju 

Anything in particular you'd like to see first?

**Comment by jennijuju** [comment]
@johnnymatthews let’s start with confirming the storage and retrieval tutorial is still up to date?

**Pull request merged**
